### ISSUE TITLE
Write usage instructions in Markdown

### ISSUE THREAD

**Issue by fedorov** [HesongHuang/scholar.py#2]
This will make the instructions better formatted and readable by the user.

See for example https://github.com/HesongHuang/scholar.py/blob/branch/README.md.

**Comment by fedorov** [comment]
See markdown tutorial here: https://guides.github.com/features/mastering-markdown/

**Comment by HesongHuang** [comment]
Done

**Comment by fedorov** [comment]
@HesongHuang I did not see the pull request with the proposed changes.

For each issue, please follow this workflow:

1) create a new branch with the name that includes issue number and some words for the description (for example, for this specific issue, the branch name could be `2-fix-instructions-formatting`)
2) make the changes to the code, commit to the branch including comments describing what you did
3) push the branch to github
4) make a pull request and reference the issue you are resolving from the pull request using # followed by the issue number
5) wait for me to review your pull request, respond to comments, and merge after I approve your changes

**Comment by fedorov** [comment]
Please follow the workflow above for the remaining issues.
