### ISSUE TITLE
Extract all of the citations and save in the file in repository

### ISSUE THREAD

**Issue by fedorov** [HesongHuang/scholar.py#3]
Right now the citations file contains only about 100 citations.

**Comment by HesongHuang** [comment]
https://github.com/HesongHuang/scholar.py/blob/%233-number-of-citation/Bibtex.json
This is the Json file of results. It is a valid json.
Please give me a feedback.

**Comment by fedorov** [comment]
Which pull request should I look at? Can you add a link here?

The file you referenced contains `\n\n` in some of the fields - can you please remove those?

**Comment by HesongHuang** [comment]
#18

**Comment by fedorov** [comment]
Resolved in #18
